name: Roblox Online Checker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download previous state
        uses: actions/download-artifact@v4
        with:
          name: state
        continue-on-error: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run script
        env:
          ROBLOX_USER_1: ${{ secrets.ROBLOX_USER_1 }}
          ROBLOX_USER_2: ${{ secrets.ROBLOX_USER_2 }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node check.js

      - name: Upload new state
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state.json

